name: coinche
description: A flutter client for coinche

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fb_auth: ^1.1.1
  google_sign_in: ^4.5.4 #for mobile google signin
  firebase_auth: ^0.15.5+3 #user auth
  firebase_analytics: ^5.0.16
  firebase_storage: ^3.1.6 # for firebase storage
  cloud_firestore: ^0.13.7 # Firestore
  firebase_core: ^0.4.5
  # UI
  flutter_signin_button: ^1.1.0 # for sign in buttons
  flash: ^1.3.1 # for alerting UI (snackbar, toast, dialogs)
  flutter_login: ^1.0.14 # animations and visuals for login
  flutter_svg: ^0.19.0
  auto_size_text: ^2.1.0
  # HTTP
  http: ^0.12.2
  requests: ^3.3.0 # For cookie-aware http requests
  json_annotation: ^3.1.0 # for json

  audioplayers: ^0.16.1
  shared_preferences: ^0.5.12
  universal_platform: ^0.1.3 # working with web too (instead of dart:io)
  tuple: ^1.0.3
  equatable: ^1.2.5 # for simple .equals()
  quiver: ^2.1.3 # For hash2 function, and other utilities
  provider: ^4.3.2+2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  # For json
  build_runner: ^1.10.3
  json_serializable: ^3.5.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/club.png
    - images/heart.png
    - images/diamond.png
    - images/spade.png
    - images/chicken.svg
    - images/face.svg
    - images/penguin.svg
    - images/vampire.svg
    - assets/sounds/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
